import './globals.css'
import Navbar from '@/components/Navbar'
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'

export const metadata = {
  title: 'Social app',
  description: 'Generated by create next app'
}

export default async function RootLayout ({ children }) {
  const cookieStore = cookies()
  const supabase = createServerComponentClient({ cookies: () => cookieStore })

  const {
    data: { session }
  } = await supabase.auth.getSession()

  return (
    <html lang='en'>
      <head>
        <link rel='shortcut icon' href='favicon.ico' />
      </head>
      <body>
        <Navbar session={session} />
        {children}
      </body>
    </html>
  )
}
