import './globals.css'
import Navbar from '@/components/Navbar'
import { Inter } from 'next/font/google'
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Reddit clone',
  description: 'Generated by create next app'
}

export default async function RootLayout ({ children }) {
  const cookieStore = cookies()
  const supabase = createServerComponentClient({ cookies: () => cookieStore })

  const {
    data: { session },
  } = await supabase.auth.getSession()

  return (
    <html lang='en'>
      <body>
        <Navbar session={session} />
        {children}
      </body>
    </html>
  )
}

